"""Interactive ``codex-rc`` setup wizard.

Creates a ``.env`` file in the current working directory by copying
``.env.example`` (looked up next to the package) and prompting for the
required Discord values. Existing ``.env`` is never overwritten without
explicit confirmation.
"""

from __future__ import annotations

import os
import shutil
import subprocess
import sys
from pathlib import Path

REQUIRED_PROMPTS: tuple[tuple[str, str, str | None], ...] = (
    (
        "CODEX_RC_DISCORD_TOKEN",
        "Discord bot token (Developer Portal → Bot → Reset Token)",
        None,
    ),
    (
        "CODEX_RC_DISCORD_APP_ID",
        "Discord application ID (Developer Portal → General Information)",
        None,
    ),
    (
        "CODEX_RC_ALLOWED_USER_IDS",
        "Your Discord user ID (the only ID allowed to drive codex)",
        None,
    ),
)

OPTIONAL_PROMPTS: tuple[tuple[str, str, str | None], ...] = (
    (
        "CODEX_RC_DISCORD_GUILD_ID",
        "Guild ID for instant slash-command registration (optional, blank to skip)",
        "",
    ),
)

DEFAULT_ENV_TEMPLATE = """\
# codex_rc configuration - generated by codex-rc setup.

CODEX_RC_DISCORD_TOKEN=
CODEX_RC_DISCORD_APP_ID=
CODEX_RC_DISCORD_GUILD_ID=
CODEX_RC_DISCORD_CHANNEL_IDS=
CODEX_RC_ALLOWED_USER_IDS=

CODEX_RC_DEFAULT_SANDBOX=workspace-write
CODEX_RC_DEFAULT_APPROVAL=on-request
CODEX_RC_TRANSPORT=ws

CODEX_RC_MEMORY_PATH=./data/state/memory.json
CODEX_RC_LOG_ROOT=./data/logs
CODEX_RC_DEBUG_ROOT=./data/debug
CODEX_RC_EVENT_LOG_MODE=errors
CODEX_RC_ERROR_LOG_RETENTION_DAYS=30
CODEX_RC_THREAD_HISTORY_MAX=100

CODEX_RC_LOG_LEVEL=WARNING
CODEX_RC_LOG_PATH=
CODEX_RC_LOG_FORMAT=text

CODEX_RC_OPS_CHANNEL_ID=
CODEX_RC_MENTION_ON_COMPLETE=
CODEX_RC_AUTO_APPROVE=false
CODEX_RC_AUTO_COMPACT_INPUT_TOKENS=0

CODEX_RC_HEALTH_HOST=127.0.0.1
CODEX_RC_HEALTH_PORT=0

CODEX_RC_SOUL_PATH=
CODEX_RC_RULES_PATH=
CODEX_RC_RULES_DIR=
"""


def _find_example(start: Path) -> Path | None:
    candidates = [
        start / ".env.example",
        Path(__file__).resolve().parent.parent.parent / ".env.example",
    ]
    for c in candidates:
        if c.is_file():
            return c
    return None


def _prompt(label: str, default: str | None) -> str:
    suffix = f" [{default}]" if default else ""
    raw = input(f"{label}{suffix}: ").strip()
    if not raw and default is not None:
        return default
    return raw


def _write_env(env_path: Path, values: dict[str, str], template: str) -> None:
    out_lines: list[str] = []
    keys_remaining = set(values)
    for line in template.splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            out_lines.append(line)
            continue
        key = stripped.split("=", 1)[0].strip()
        if key in values:
            out_lines.append(f"{key}={values[key]}")
            keys_remaining.discard(key)
        else:
            out_lines.append(line)
    # Append any new keys that the template did not already contain.
    for k in sorted(keys_remaining):
        out_lines.append(f"{k}={values[k]}")
    env_path.write_text("\n".join(out_lines) + "\n", encoding="utf-8")
    try:
        env_path.chmod(0o600)
    except OSError:
        pass


def _codex_login_hint() -> str:
    try:
        result = subprocess.run(
            ["codex", "login", "status"],
            capture_output=True,
            text=True,
            timeout=10,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return "missing"
    return "ok" if result.returncode == 0 else "missing"


def run_guided(cwd: Path | None = None, stdout=sys.stdout) -> int:
    """Codex-first setup flow.

    This is intentionally still terminal-safe: Codex can call this command,
    read the prompts, and tell the user exactly which Discord Developer Portal
    value to paste next.
    """
    here = (cwd or Path.cwd()).expanduser().resolve()
    print(
        "\ncodex_rc guided setup\n"
        "\n"
        "Codex CLI should already be installed and logged in. This project uses\n"
        "your local Codex login; it does not ask for an OpenAI API key.\n",
        file=stdout,
    )
    if _codex_login_hint() != "ok":
        print(
            "Before continuing, run one of:\n"
            "  codex login\n"
            "  codex login --device-auth   # headless / SSH\n",
            file=stdout,
        )
    print(
        "You will need three Discord values:\n"
        "  1. Bot Token: Developer Portal -> Bot -> Reset Token\n"
        "  2. Application ID: Developer Portal -> General Information\n"
        "  3. Your Discord User ID: enable Developer Mode, right-click yourself\n"
        "\n"
        "Optional but recommended:\n"
        "  - Guild ID for instant slash command registration\n",
        file=stdout,
    )
    code = run(cwd=here, stdout=stdout)
    if code != 0:
        return code

    from .gateway import invite_url_from_env, print_doctor

    invite = invite_url_from_env(here)
    if invite:
        print(
            "\nInvite the bot with this URL:\n"
            f"{invite}\n"
            "\n"
            "After inviting it, run:\n"
            f"  codex-rc gateway doctor --fix --cwd {here}\n"
            f"  codex-rc gateway run --cwd {here}\n",
            file=stdout,
        )
    print("\nReadiness check:", file=stdout)
    return print_doctor(here, fix=True)


def run(cwd: Path | None = None, stdout=sys.stdout) -> int:
    """Execute the wizard. Returns a process exit code."""
    here = (cwd or Path.cwd()).resolve()
    env_path = here / ".env"
    example = _find_example(here)
    template = example.read_text(encoding="utf-8") if example else DEFAULT_ENV_TEMPLATE

    if env_path.exists():
        ans = input(f"{env_path} already exists. Overwrite? [y/N]: ").strip().lower()
        if ans not in {"y", "yes"}:
            print("aborted; nothing changed.", file=stdout)
            return 0
        shutil.copy(env_path, env_path.with_name(".env.bak"))
        print(f"backed up existing config to {env_path.with_suffix('.env.bak')}", file=stdout)

    print("\ncodex_rc setup — fill in the required Discord values.\n", file=stdout)

    values: dict[str, str] = {}
    for key, label, default in REQUIRED_PROMPTS:
        existing = os.environ.get(key, "")
        v = _prompt(label, existing or default)
        if not v:
            print(f"{key} is required; aborting.", file=sys.stderr)
            return 1
        values[key] = v

    for key, label, default in OPTIONAL_PROMPTS:
        existing = os.environ.get(key, "")
        v = _prompt(label, existing or default)
        if v:
            values[key] = v

    _write_env(env_path, values, template)
    print(f"\nwrote {env_path} (chmod 0600).", file=stdout)
    print("next: `codex-rc gateway doctor --fix` then `codex-rc gateway run`.", file=stdout)
    return 0


def main() -> None:  # pragma: no cover — console script
    raise SystemExit(run())


__all__ = ["run", "run_guided", "main"]
