#!/usr/bin/env bash
# Regenerate Codex app-server protocol bindings.
#
#  1. `codex app-server generate-json-schema --experimental --out tmp/schema`
#  2. datamodel-code-generator → src/codex_rc/protocol/v2.py
#
# Re-run whenever Codex CLI is updated.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

SCHEMA_DIR="tmp/schema"
OUT_FILE="src/codex_rc/protocol/v2.py"

if ! command -v codex >/dev/null 2>&1; then
    echo "error: \`codex\` CLI not found on PATH" >&2
    echo "  install with: brew install --cask codex" >&2
    exit 1
fi

if ! command -v datamodel-codegen >/dev/null 2>&1; then
    echo "error: \`datamodel-codegen\` not found" >&2
    echo "  install dev deps: uv pip install -e \".[dev]\"" >&2
    exit 1
fi

CODEX_VERSION="$(codex --version)"
echo "==> Codex version: ${CODEX_VERSION}"

rm -rf "$SCHEMA_DIR"
mkdir -p "$SCHEMA_DIR"

echo "==> Generating JSON Schema bundle (experimental)"
codex app-server generate-json-schema --experimental --out "$SCHEMA_DIR"

V2_BUNDLE="$SCHEMA_DIR/codex_app_server_protocol.v2.schemas.json"
if [[ ! -s "$V2_BUNDLE" ]]; then
    echo "error: V2 schema bundle missing at $V2_BUNDLE" >&2
    exit 2
fi

echo "==> Generating Pydantic models → $OUT_FILE"
mkdir -p "$(dirname "$OUT_FILE")"
datamodel-codegen \
    --input "$V2_BUNDLE" \
    --input-file-type jsonschema \
    --output "$OUT_FILE" \
    --output-model-type pydantic_v2.BaseModel \
    --target-python-version 3.12 \
    --use-double-quotes \
    --use-standard-collections \
    --use-union-operator \
    --use-schema-description \
    --field-constraints \
    --reuse-model \
    --collapse-root-models \
    --disable-timestamp \
    --use-default-kwarg \
    --custom-file-header "# Auto-generated by scripts/gen_protocol.sh from ${CODEX_VERSION}. Do not edit."

echo "==> Done."
echo "    Source schema:  $V2_BUNDLE"
echo "    Output module:  $OUT_FILE"
